services:
  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: Shakalor24
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - emailnet
    ports:
     - 5433:5432

volumes:
  pgdata:

networks:
  emailnet:
